// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoe-_MQKB8VJW-cPEunOH9yaBkXrPeH0U',
    appId: '1:432256544412:web:3942651f452b4e514bc759',
    messagingSenderId: '432256544412',
    projectId: 'fir-task-423b2',
    authDomain: 'fir-task-423b2.firebaseapp.com',
    storageBucket: 'fir-task-423b2.firebasestorage.app',
    measurementId: 'G-XB2FK5YMV9',
    databaseURL: 'https://fir-task-423b2-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDQu-oUuPBmpgufffDoICuTSCaX7z0lPY',
    appId: '1:432256544412:android:c4c254a4d95f4c654bc759',
    messagingSenderId: '432256544412',
    projectId: 'fir-task-423b2',
    storageBucket: 'fir-task-423b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzo7J4xqXNPk88YHqWy4bOUBi7TtEEHnA',
    appId: '1:432256544412:ios:74d00d0ebf2027494bc759',
    messagingSenderId: '432256544412',
    projectId: 'fir-task-423b2',
    storageBucket: 'fir-task-423b2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzo7J4xqXNPk88YHqWy4bOUBi7TtEEHnA',
    appId: '1:432256544412:ios:74d00d0ebf2027494bc759',
    messagingSenderId: '432256544412',
    projectId: 'fir-task-423b2',
    storageBucket: 'fir-task-423b2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoe-_MQKB8VJW-cPEunOH9yaBkXrPeH0U',
    appId: '1:432256544412:web:67862412839804504bc759',
    messagingSenderId: '432256544412',
    projectId: 'fir-task-423b2',
    authDomain: 'fir-task-423b2.firebaseapp.com',
    storageBucket: 'fir-task-423b2.firebasestorage.app',
    measurementId: 'G-ZZF21DFMMX',
  );
}
